#%RAML 1.0
title: Documentation des services offerts par cette application.
mediaType: application/json
types:

/api:
    /test
        get:
            description: Test des fonctionnalité RAML
            