#%RAML 1.0
title: Documentation des services offerts par cette application.
mediaType: application/json
types:
    Piscine:
        properties:
            id:number
            id_uev:number
            type:string
            nom:string
            nom_arr:string
            adresse:string
            propriete:string
            point_x:string
            point_y:string
            equipement:string
            longitude:string
            latitude:string
    Patinoire:
        properties:
            id:number
            nom:string
            date_maj:string
            deblaye:string
            arrose:string
            resurface:string
            nom_arr:string
    Glissade:
        properties:
            id:number
            nom:string
            ouvert:string
            deblaye:string
            cle:string
            date_maj:string
            nom_arr:string
    NouveauProfil:
        properties:
            nom: string
            email: string
            liste_arr: string[]


/api:
    /installations:
        get:
            description: "Retourne les installations d'un arrondissement donné en paramètre. Les installations ne contiennent pas nécessairement les même informations."
            queryParameters:
                arrondissement: 
                    type:string
                    required: true
            responses:
                200:
                    description: Les installations de l'arrondissement donné.
                    body:
                        application/json:
                            type: |
                                Glissade
                                Piscine
                                Patinoire

                            example: |
                             {
                                "piscines":[
                                    {
                                        "adresse": "une place",
                                        "equipement": "equi",
                                        "gestion": "Municipale",
                                        "id": 123,
                                        "id_uev": 1234567,
                                        "latitude": "43.251235",
                                        "longitude": "-14.335155",
                                        "nom": "Parc fictif", 
                                        "nom_arr": "Verdun",
                                        "point_x": "4515234.5324",
                                        "point_y": "1234564343",
                                        "propriete": "Municipale",
                                        "type": "Jeu d'eau"
                                    }
                                ],
                                "patinoires":[
                                    {
                                        "arrose":, "0",
                                        "date_maj": "2021-03-21 13:11:29",
                                        "deblaye": "0",
                                        "id": 3,
                                        "nom": "Aire de glissade, Parc Confédération ()", 
                                        "nom_arr": "Verdun", 
                                        "resurface" : "0"
                                    }
                                ],
                                "glissades":[
                                    {
                                        "cle": "ver",
                                        "date_maj": "2021-11-15 12:18:10",
                                        "deblaye": "0",
                                        "id": 3,
                                        "nom": "Glissade, Parc Arthur-Therrien",
                                        "nom_arr": "Verdun",
                                        "ouvert": "0"
                                    }
                                ]
                             }
                400:
                    description: Le paramètre 'arrondissement' n'a pas été donné.
                404:
                    description: L'arrondissement donné en paramètre n'a pas été trouvé.
    /installation:
        get:
            description: Retourne l'installation correspondant au nom donné en paramètre.
            queryParameters:
                installation:
                    type:string
                    required:true
            responses:
                200:
                    description: L'opération s'est déroulée avec succès
                    body:
                        application/json:
                            type: |
                                Glissade
                                Piscine
                                Patinoire
                        

                400:
                    description: Le paramètre 'installation' n'a pas été donné.

                404:
                    description: Le nom de l'installation n'est pas valide.

    /profil:
        post:
            description:
            body:
                type: |
                    NouveauProfil
                example: |
                    {
                        "nom":"Jacque",
                        "email":"fictif@courrier.com",
                        "liste_arr": [
                            "Verdun",
                            "LaSalle",
                            "Le Sud-Ouest"
                        ]
                    }
            responses:
                200:
                    description: 
                201:
                    description: Le nouveau profil a été créé avec succès.
                400:
                    description: Il y a une/des erreurs dans la requête.




            